fix: error TS2739
Type '{}' is missing the following properties from type '{ hideNavigation: boolean; noPadding: boolean; }': hideNavigation, noPadding